@startuml
autonumber 1

box "Modify Comment" #FFF

User -> CAFFManager: modifyComment(caffId, newComment)
activate CAFFManager

note left of CAFFManager #DDD
Tasks will be logged
end note

CAFFManager -> UserManager: checkAuth(token)
activate UserManager

CAFFManager <<-- UserManager: Success
deactivate UserManager

alt auth success

CAFFManager -> CAFFManager: modifyComment(newComment)
activate CAFFManager

CAFFManager -> CAFFDatabase: modifyCAFF(caffId, caff)
activate CAFFDatabase

CAFFManager <<-- CAFFDatabase
deactivate CAFFDatabase

deactivate CAFFManager

CAFFManager -->> User: Success

else else

CAFFManager -->> User: Faliure
deactivate CAFFManager

end

end box

@enduml