version: "3.4"

services:
    db:
      image: "mcr.microsoft.com/mssql/server:2022-latest" #19
      container_name: db
      ports:
        - "1433:1433"
      environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:7231"
          - "8081:80"
        depends_on:
          - db
