@startuml
autonumber 1

box "CAFF file upload" #FFF

User -> CAFFManager: uploadCAFF(name, password, caffFile)
activate CAFFManager 

note left of CAFFManager #DDD
Tasks will be logged
end note

CAFFManager -> UserManager: checkAuth(token)
activate UserManager

UserManager -->> CAFFManager: isSuccess
deactivate UserManager

alt auth success

CAFFManager -> CAFFParser: ParseFile(caffFile)
activate CAFFParser

CAFFManager <<-- CAFFParser: caff
deactivate CAFFParser

CAFFManager -> CAFFManager: SaveCaffFile(caff)
activate CAFFManager

deactivate CAFFManager


CAFFManager -->> User: uploadSuccessful

else else


User <<-- CAFFManager: Failure
deactivate CAFFManager 

end

end box

@enduml