@startuml
box Login #FFF

autonumber 1
User -> UserManager: loginUser(name, password)
activate UserManager

note left of UserManager #DDD
Tasks will be logged
end note

UserManager -> UserManager: checkCredentials(name, password)
activate UserManager

UserManager -> UserDatabase: getCredentialsFromDatabase(name)
activate UserDatabase

UserManager <<-- UserDatabase: Credentials
deactivate UserDatabase


alt credentials are valid

User <<-- UserManager: Success
else else
   UserManager -->> UserManager
   deactivate UserManager



   User <<-- UserManager : Faliure
deactivate UserManager

end

box end

@enduml 