@startuml
left to right direction
:User: <|-up- :Admin:

rectangle Identity{
  User -up-> (Register)
  User --> (Login)
  (Login) .left.> (Register) : <<extend>>
}

rectangle CAFF {
  User --> (Download)
  User --> (Search)
  (Manage own CAFF) as ManageOwnCAFF
  (Manage CAFF of\n other users) as ManageOthersCAFF
  User --> ManageOwnCAFF
  (Upload) .up.> ManageOwnCAFF : <<extend>>
  Admin --> ManageOthersCAFF
  (Modify title) .up.> ManageOwnCAFF : <<extend>>
  (Modify title) .up.> ManageOthersCAFF : <<extend>>
  (Delete) as DeleteCAFF
  DeleteCAFF .up.> ManageOwnCAFF : <<extend>>
  DeleteCAFF .up.> ManageOthersCAFF : <<extend>>
}

rectangle Comment {
  (Manage own Comment) as ManageOwnComment
  (Manage Comment of\n other users) as ManageOthersComment
  (Create) ..> ManageOwnComment : <<extend>>
  (Modify) ..> ManageOwnComment : <<extend>>
  (Modify) ..> ManageOthersComment : <<extend>>
  (Delete) as DeleteComment
  DeleteComment ..> ManageOwnComment : <<extend>>
  DeleteComment ..> ManageOthersComment : <<extend>>
  User -left-> ManageOwnComment
  Admin -up-> ManageOthersComment
}

@enduml
