@startuml usecase_admin
left to right direction

rectangle Identity{
  (Modify others' Profile) as ModifyOthersProfile
  (Delete others' Profile) as DeleteOthersProfile
  (ModifyOthersProfile) .down.> (Login) : <<include>>
  (DeleteOthersProfile) .down.> (Login) : <<include>>
}

Admin --> (Login)
Admin --> ModifyOthersProfile
Admin --> DeleteOthersProfile

rectangle CAFF {
  (Modify others' CAFF\nfile's title) as ModifyOthersCAFF
  (Delete others' CAFF\nfile) as DeleteOwnCAFF
  ModifyOthersCAFF ..> (Login) : <<include>>
  DeleteOwnCAFF ..> (Login) : <<include>>
}

Admin --> ModifyOthersCAFF
Admin --> DeleteOwnCAFF

rectangle Comment {
  (Modify others' Comment) as ModifyOthersComment
  (Delete others' Comment) as DeleteOwnComment
  ModifyOthersComment ..> (Login) : <<include>>
  DeleteOwnComment ..> (Login) : <<include>>
}

Admin -down-> ModifyOthersComment
Admin -down-> DeleteOwnComment

@enduml
